In [2]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [28]:
# Read in the S&P 500 constituents csv file and clean the data
sp_df = pd.read_csv('sp500.csv')

#Make column names more readable
sp_df.columns = ['RIC', 'Company_Name', 'market_cap', 'net_debt', 'ev', 'PE_FY0', 'PE_FY1', 'PE_FY2', 'PCF_FY0', 'PCF_FY1', 'PCF_FY2', 'PRev_FY0', 'PRev_FY1', 'PRev_FY2', 'PBV_FY0', 'PBV_FY1', 'PBV_FY2', 'EV_EBITDA_FY0', 'EV_EBITDA_FY1', 'EV_EBITDA_FY2', 'EV_Rev_FY0', 'EV_Rev_FY1', 'EV_Rev_FY2']

# Clense columns of commas and convert to float
sp_df['market_cap'] = sp_df['market_cap'].str.replace(',', '').astype(float)
sp_df['ev'] = sp_df['ev'].str.replace(',', '').astype(float)
sp_df['net_debt'] = sp_df['net_debt'].str.replace(',', '').astype(float)
# Convert all other columns to float
sp_df.iloc[:, 2:] = sp_df.iloc[:, 2:].apply(pd.to_numeric, errors='coerce')

#Sort by market cap
sp_df.sort_values("market_cap", ascending=False, inplace=True)

#Show the top 10 companies by market cap
sp_df.head(10)

/var/folders/80/4sg7_lcn221gzdjhyy7hm31h0000gn/T/ipykernel_49944/2709886681.py:12: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  sp_df.iloc[:, 2:] = sp_df.iloc[:, 2:].apply(pd.to_numeric, errors='coerce')

,RIC,Company_Name,market_cap,net_debt,ev,PE_FY0,PE_FY1,PE_FY2,PCF_FY0,PCF_FY1,...,PRev_FY2,PBV_FY0,PBV_FY1,PBV_FY2,EV_EBITDA_FY0,EV_EBITDA_FY1,EV_EBITDA_FY2,EV_Rev_FY0,EV_Rev_FY1,EV_Rev_FY2
0,AAPL.OQ,Apple Inc,2623120.43,59755.0,2682875.43,24.61,27.77,25.15,22.14,22.74,...,6.38,47.33,44.29,33.29,19.08,21.57,20.22,6.32,6.94,6.52
1,MSFT.OQ,Microsoft Corp,2270872.26,-39754.0,2231118.26,26.62,31.55,27.89,22.17,27.50,...,9.65,11.51,10.17,8.34,19.16,21.82,18.85,9.47,10.56,9.48
2,GOOGL.OQ,Alphabet Inc,1332303.41,-101033.0,1231270.41,19.36,19.58,16.61,15.30,13.62,...,3.98,4.43,4.73,3.97,11.53,10.52,9.16,3.70,4.10,3.68
3,GOOG.OQ,Alphabet Inc,1332303.41,-101033.0,1231270.41,19.36,19.88,17.03,15.30,13.78,...,4.02,4.43,4.84,4.12,11.53,10.58,9.28,3.70,4.11,3.71
4,AMZN.OQ,Amazon.com Inc,1067076.78,25994.0,1093070.78,NaN,66.70,41.16,21.83,13.85,...,1.71,5.89,5.77,4.56,16.24,12.12,10.12,1.71,1.94,1.74
5,BRKb.N,Berkshire Hathaway Inc,704365.96,-5841.0,706781.96,NaN,19.95,17.61,NaN,NaN,...,1.74,1.45,1.39,1.29,13.49,NaN,NaN,2.27,2.15,1.97
6,NVDA.OQ,NVIDIA Corp,680781.40,-2343.0,678438.40,116.88,60.21,45.40,86.36,53.76,...,18.10,22.72,23.54,17.87,63.34,47.77,35.83,18.49,22.42,18.03
7,META.OQ,Meta Platforms Inc,598449.18,-25462.0,572987.18,13.16,19.79,15.86,9.74,11.33,...,4.27,2.50,4.30,3.45,6.76,8.95,7.76,2.45,4.52,4.09
8,TSLA.OQ,Tesla Inc,510924.09,-19726.0,492379.09,34.02,47.08,33.96,26.54,32.43,...,4.02,8.72,9.61,7.56,21.18,28.98,20.73,4.56,4.96,3.87
9,V.N,Visa Inc,462287.04,4012.0,468184.04,25.37,26.21,22.98,23.99,23.00,...,12.76,11.05,10.86,9.38,18.08,20.49,18.23,12.75,14.36,12.92

In [30]:
# Do the same for the Russell 1000

r_df = pd.read_csv('russell1000.csv')

r_df.columns = ['RIC', 'Company_Name', 'market_cap', 'net_debt', 'ev', 'PE_FY0', 'PE_FY1', 'PE_FY2', 'PCF_FY0', 'PCF_FY1', 'PCF_FY2', 'PRev_FY0', 'PRev_FY1', 'PRev_FY2', 'PBV_FY0', 'PBV_FY1', 'PBV_FY2', 'EV_EBITDA_FY0', 'EV_EBITDA_FY1', 'EV_EBITDA_FY2', 'EV_Rev_FY0', 'EV_Rev_FY1', 'EV_Rev_FY2']

r_df['market_cap'] = r_df['market_cap'].str.replace(',', '').astype(float)
r_df['ev'] = r_df['ev'].str.replace(',', '').astype(float)
r_df['net_debt'] = r_df['net_debt'].str.replace(',', '').astype(float)

r_df.iloc[:, 2:] = r_df.iloc[:, 2:].apply(pd.to_numeric, errors='coerce')
r_df.sort_values("market_cap", ascending=False, inplace=True)

r_df.head(10)

/var/folders/80/4sg7_lcn221gzdjhyy7hm31h0000gn/T/ipykernel_49944/3256515493.py:11: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  r_df.iloc[:, 2:] = r_df.iloc[:, 2:].apply(pd.to_numeric, errors='coerce')

,RIC,Company_Name,market_cap,net_debt,ev,PE_FY0,PE_FY1,PE_FY2,PCF_FY0,PCF_FY1,...,PRev_FY2,PBV_FY0,PBV_FY1,PBV_FY2,EV_EBITDA_FY0,EV_EBITDA_FY1,EV_EBITDA_FY2,EV_Rev_FY0,EV_Rev_FY1,EV_Rev_FY2
0,AAPL.OQ,Apple Inc,2623120.43,59755.0,2682875.43,24.61,27.79,25.17,22.14,22.74,...,6.38,47.33,44.29,33.29,19.08,21.59,20.26,6.32,6.94,6.52
1,MSFT.OQ,Microsoft Corp,2270872.26,-39754.0,2231118.26,26.62,31.55,27.89,22.17,27.50,...,9.65,11.51,10.17,8.34,19.16,21.82,18.85,9.47,10.56,9.48
2,GOOGL.OQ,Alphabet Inc,1332303.41,-101033.0,1231270.41,19.36,19.58,16.61,15.30,13.62,...,3.98,4.43,4.73,3.97,11.53,10.52,9.16,3.70,4.10,3.68
3,GOOG.OQ,Alphabet Inc,1332303.41,-101033.0,1231270.41,19.36,19.88,17.03,15.30,13.78,...,4.02,4.43,4.84,4.12,11.53,10.58,9.28,3.70,4.11,3.71
4,AMZN.OQ,Amazon.com Inc,1067076.78,25994.0,1093070.78,NaN,66.70,41.16,21.83,13.85,...,1.71,5.89,5.77,4.56,16.24,12.12,10.12,1.71,1.94,1.74
5,BRKb.N,Berkshire Hathaway Inc,704365.96,-5841.0,706781.96,NaN,19.95,17.61,NaN,NaN,...,1.74,1.45,1.39,1.29,13.49,NaN,NaN,2.27,2.15,1.97
6,NVDA.OQ,NVIDIA Corp,680781.40,-2343.0,678438.40,116.88,60.21,45.40,86.36,53.76,...,18.10,22.72,23.54,17.87,63.34,47.77,35.83,18.49,22.42,18.03
7,META.OQ,Meta Platforms Inc,598449.18,-25462.0,572987.18,13.16,19.79,15.86,9.74,11.33,...,4.27,2.50,4.30,3.45,6.76,8.95,7.76,2.45,4.52,4.09
8,TSLA.OQ,Tesla Inc,510924.09,-19726.0,492379.09,34.02,47.08,33.96,26.54,32.43,...,4.02,8.72,9.61,7.56,21.18,28.98,20.73,4.56,4.96,3.87
9,V.N,Visa Inc,462287.04,4012.0,468184.04,25.37,26.21,22.98,23.99,23.00,...,12.76,11.05,10.86,9.38,18.08,20.49,18.23,12.75,14.36,12.92

In [18]:
# Mark the S&P 500 constituents in the Russell 1000
r_df["in_sp"] = r_df["RIC"].isin(sp_df["RIC"])

# Create a subset of the Russell 1000 that is not in the S&P 500
r_df_subset = r_df[r_df["in_sp"] == False]

In [34]:
# Get the market cap of the 50% perncentile of the S&P
market_cap = sp_df["market_cap"].quantile(0.5)

In [35]:
# Show the of companies in the Russell 1000 that are greater than the 30% percentile of the S&P 500
r_df_subset[ r_df["market_cap"] > market_cap]

/var/folders/80/4sg7_lcn221gzdjhyy7hm31h0000gn/T/ipykernel_49944/1490532110.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  r_df_subset[ r_df["market_cap"] > market_cap]

,RIC,Company_Name,market_cap,net_debt,ev,PE_FY0,PE_FY1,PE_FY2,PCF_FY0,PCF_FY1,...,PBV_FY0,PBV_FY1,PBV_FY2,EV_EBITDA_FY0,EV_EBITDA_FY1,EV_EBITDA_FY2,EV_Rev_FY0,EV_Rev_FY1,EV_Rev_FY2,in_sp
78,BX.N,Blackstone Inc,98797.56,9313.62,119734.17,31.45,18.21,13.54,17.59,16.66,...,6.88,8.44,6.63,28.25,17.66,13.18,13.07,10.80,7.95,False
101,UBER.N,Uber Technologies Inc,75500.06,5116.00,81780.06,NaN,810.24,39.74,NaN,24.78,...,6.76,7.92,5.47,NaN,22.91,15.29,1.75,2.17,1.85,False
103,ABNB.OQ,Airbnb Inc,74125.14,-7635.00,66490.14,30.65,34.84,28.46,29.33,19.44,...,9.84,8.84,6.20,23.48,19.71,16.14,5.54,6.91,5.93,False
129,SCCO.N,Southern Copper Corp,57943.97,3811.60,61819.17,17.69,19.49,16.16,13.55,15.97,...,5.78,6.38,5.59,9.69,10.68,9.10,5.05,5.87,5.26,False
140,PANW.OQ,Palo Alto Networks Inc,54169.85,333.40,54503.25,NaN,44.45,37.64,156.17,22.13,...,236.72,36.41,19.09,126.64,30.66,25.04,9.05,7.91,6.50,False
145,VMW.N,VMware Inc,52193.56,5388.00,57581.56,39.46,16.88,14.97,20.50,10.94,...,33.88,27.17,14.43,17.67,10.80,9.37,4.30,4.04,3.77,False
150,SNOW.N,Snowflake Inc.,50462.75,-4007.87,46467.06,NaN,259.90,149.96,NaN,94.90,...,9.27,9.22,8.62,NaN,181.65,102.51,22.42,16.14,11.75,False
156,LULU.OQ,Lululemon Athletica Inc,48643.88,-1154.87,47489.01,46.55,32.90,28.39,34.71,29.07,...,13.07,12.27,9.68,19.08,19.48,17.14,4.75,5.06,4.47,False
167,WDAY.OQ,Workday Inc,47117.28,-3145.46,43971.82,NaN,35.09,28.80,273.78,23.57,...,8.38,7.23,5.87,138.74,21.47,17.57,7.00,6.10,5.20,False
182,KKR.N,KKR & Co Inc,42710.96,30061.98,109818.79,NaN,13.27,10.29,NaN,12.44,...,2.41,1.61,1.37,282.07,24.62,19.40,14.18,16.52,13.16,False
205,TEAM.OQ,Atlassian Corp,38455.92,-673.18,37782.74,NaN,95.84,71.50,NaN,53.81,...,142.35,49.01,34.14,NaN,57.90,47.50,17.00,10.78,8.86,False
215,SGEN.OQ,Seagen Inc,37219.54,-1490.27,35729.27,NaN,NaN,NaN,NaN,NaN,...,8.55,28.68,25.35,NaN,NaN,NaN,11.27,15.18,11.35,False
221,SQ.N,Block Inc,36463.04,-1039.03,35452.49,67.28,35.00,24.54,40.72,21.07,...,2.19,2.01,2.01,77.42,26.37,18.85,2.09,1.76,1.54,False
223,LENb.N,Lennar Corp,36028.47,978.95,37144.45,5.59,NaN,NaN,5.38,NaN,...,1.06,NaN,NaN,3.73,NaN,NaN,0.79,NaN,NaN,False
226,LNG.A,Cheniere Energy Inc,35292.11,21559.00,60389.11,26.61,6.82,11.80,10.12,5.34,...,NaN,NaN,NaN,11.28,6.87,8.73,1.92,3.08,3.00,False
242,MRVL.OQ,Marvell Technology Inc,33564.89,3581.10,37145.99,NaN,25.53,17.26,30.07,19.83,...,2.42,2.17,2.20,21.92,21.02,17.04,6.98,6.74,5.73,False
245,APO.N,Apollo Global Management Inc,33120.66,-2930.00,37022.66,NaN,9.11,7.94,NaN,11.55,...,91.63,3.68,2.49,2.84,7.86,7.09,3.46,8.43,6.63,False
250,DELL.N,Dell Technologies Inc,32304.63,20981.00,53382.63,13.02,8.36,7.17,5.70,5.28,...,NaN,NaN,NaN,5.49,6.23,5.80,0.50,0.61,0.59,False
254,GFS.OQ,Globalfoundries Inc,31890.30,-118.00,31819.30,20.54,24.77,18.48,9.17,10.11,...,2.98,2.78,2.47,9.55,10.17,8.32,3.60,3.98,3.52,False
261,BFa.N,Brown-Forman Corp,30972.00,2600.00,33572.00,38.67,NaN,NaN,35.34,NaN,...,11.80,NaN,NaN,25.61,NaN,NaN,8.35,NaN,NaN,False
265,IBKR.OQ,Interactive Brokers Group Inc,30197.85,7515.00,46944.85,19.29,12.36,12.06,3.86,NaN,...,2.61,NaN,NaN,22.33,14.08,14.58,11.93,10.94,10.88,False
269,TTD.OQ,Trade Desk Inc,29987.40,-1446.59,28540.82,419.80,52.02,40.25,207.88,51.99,...,10.39,12.66,8.91,121.96,39.84,30.66,12.99,15.12,12.07,False